name: bbmobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ui
  cupertino_icons: ^1.0.6
  infinite_scroll_pagination: ^4.0.0

  # network
  dio: ^5.7.0
  shared_preferences: ^2.0.13

  jwt_decoder: ^2.0.1

  # state management

  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  meta: ^1.9.1

  # utils
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.9.0
  auto_route: ^9.2.2
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.7.0
  auto_route_generator: ^9.0.0
  json_serializable: ^6.8.0
  flutter_launcher_icons: 0.13.1
  freezed: ^2.5.2

flutter_icons:
  image_path: "assets/img/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "assets/img/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/img/ic_launcher_foreground.png"

flutter_gen:
  output: lib/utils

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  assets:
    - assets/img/
    - .env
  uses-material-design: true
